# fly.toml app configuration file generated for minecraft-bbz on 2025-12-20T09:17:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minecraft-bbz'
primary_region = 'fra'
kill_signal = 'SIGINT'
kill_timeout = '1m0s'

[env]
ALLOW_FLIGHT = 'FALSE'
AUTOSTOP_PKILL_USE_SUDO = 'TRUE'
AUTOSTOP_TIMEOUT_EST = '300'
AUTOSTOP_TIMEOUT_INIT = '300'
AUTOPAUSE_TIMEOUT_KN = '30'
DIFFICULTY = 'normal'
ENABLE_AUTOSTOP = 'TRUE'
ENABLE_COMMAND_BLOCK = 'TRUE'
ENABLE_WHITELIST = 'TRUE'
EULA = 'TRUE'
EXISTING_OPS_FILE = 'SYNCHRONIZE'
MAX_PLAYERS = '8'
MEMORY = '7000M'
MODE = 'survival'
MOTD = '\u00a7fDu bisch e Suchti, dir isch l\u00e4ngwilig und du s\u00f6tsch eigentlech \u00f6bbis Produktivs mache?'
SERVER_ICON = 'server-icon.png'
OPS = 'technat,duffy_26'
OVERRIDE_WHITELIST = 'TRUE'
SERVER_NAME = 'bbz'
SERVER_HOST = '0.0.0.0'
SIMULATION_DISTANCE = '10'
SPAWN_X = '-58'
SPAWN_Y = '98'
SPAWN_Z = '58'
SPAWN_RADIUS = '0'
SYNC_CHUNK_WRITES = 'FALSE'
TUNE_VIRTUALIZED = 'TRUE'
TYPE = 'VANILLA'
USE_MEOWICE_FLAGS = 'TRUE'
USE_NATIVE_TRANSPORT = 'TRUE'
STOP_DURATION = '50'              # just a bit less than the kill_timeout of the fly machine
VERSION = '1.21.11'
VIEW_DISTANCE = '10'
WHITELIST = 'technat,duffy_26,tobidrglobi,Blackminty,grosseklappe2,TIBO_15,DoppuG'

[build]
image = 'itzg/minecraft-server:java17-1.21.11'

[deploy]
strategy = 'rolling'

[[vm]]
cpu_kind = "shared"
cpus = 2
memory = '4GB'
persist_rootfs = "always"

[[mounts]]
source = 'mc_server'
destination = '/data'
initial_size = '1GB'               # min size
scheduled_snapshots = true         # A snapshot a day
snapshot_retention = 7             # keep snapshots this long
auto_extend_size_threshold = 90    # at 90% add 
auto_extend_size_increment = '1GB' # 1GB
auto_extend_size_limit = '5GB'     # up to max 5GB

[[services]]
protocol = "tcp"
internal_port = 25565
auto_stop_machines = 'off' # server will shutdown itself when no active players
auto_start_machines = false # start again when connection attemps are made
min_machines_running = 0   # scale to zero
[[services.ports]]
port = 25565 # externally published port
# [[services.tcp_checks]]
# grace_period = '30s' # start as fast as possible
# interval = '5s'      # check every 5s if the server is up
# timeout = '1s'       # only ever wait 1s for a response
