services:
  backups-fische:
    image: itzg/mc-backup
    restart: unless-stopped
    environment:
      BACKUP_INTERVAL: "24h"
      RCON_HOST: fische
      PAUSE_IF_NO_PLAYERS: "true"
      BACKUP_METHOD: "restic"
    env_file:
      - .env
      - .fische-env
    volumes:
      - ./fische_data:/data:ro
