name: Deploy fische server
on:
  push:
    branches:
      - main
    paths:
      - fische/**
      - .github/workflows/fly-fische.yml

jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORG_API_TOKEN }}
    runs-on: ubuntu-latest
    concurrency: fische
    environment: fische
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy server
        working-directory: fische
        run: flyctl deploy --remote-only