name: Deploy fische server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_ORG_API_TOKEN }}
    runs-on: ubuntu-latest
    concurrency: fische
    environment: fische
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Set secrets for app
        run: |
          # flyctl secrets set FLATNOTES_USERNAME=${{ secrets.FLATNOTES_USERNAME }} --stage
          # flyctl secrets set FLATNOTES_PASSWORD=${{ secrets.FLATNOTES_PASSWORD }} --stage
          # flyctl secrets set FLATNOTES_SECRET_KEY=${{ secrets.FLATNOTES_SECRET_KEY }} --stage
      - name: Deploy Prod app
        working-directory: fische
        run: flyctl deploy --remote-only